const MODAL_VERBS = [
  "will",
  "won't",
  "would",
  "wouldn't",
  "can",
  "can't",
  "could",
  "could't",
  "may",
  "may not",
  "might",
  "mightn't",
  "must",
  "mustn't",
  "shall",
  "shan't",
  "should",
  "shouldn't",
  "ought to",
  "oughtn't to",
  "needn't",
];

const SUBJECT_PRONOUNS = ["I", "you", "he", "she", "it", "we", "they"];
const SENTENCE_TYPES = ["Statement", "Question", "Negative"];

const VERBS = {
  accept: {
    head: "accept",
    preterite: "accepted",
    pastParticiple: "accepted",
    presentParticiple: "accepting",
    thirdPersonSingular: "accepts",
  },
  allow: {
    head: "allow",
    preterite: "allowed",
    pastParticiple: "allowed",
    presentParticiple: "allowing",
    thirdPersonSingular: "allows",
  },
  ask: {
    head: "ask",
    preterite: "asked",
    pastParticiple: "asked",
    presentParticiple: "asking",
    thirdPersonSingular: "asks",
  },
  be: {
    head: "be",
    preterite: "was/were",
    pastParticiple: "been",
    presentParticiple: "being",
    thirdPersonSingular: "is",
  },
  become: {
    head: "become",
    preterite: "became",
    pastParticiple: "become",
    presentParticiple: "becoming",
    thirdPersonSingular: "becomes",
  },
  begin: {
    head: "begin",
    preterite: "began",
    pastParticiple: "begun",
    presentParticiple: "beginning",
    thirdPersonSingular: "begins",
  },
  believe: {
    head: "believe",
    preterite: "believed",
    pastParticiple: "believed",
    presentParticiple: "believing",
    thirdPersonSingular: "believes",
  },
  break: {
    head: "break",
    preterite: "broke",
    pastParticiple: "broken",
    presentParticiple: "breaking",
    thirdPersonSingular: "breaks",
  },
  bring: {
    head: "bring",
    preterite: "brought",
    pastParticiple: "brought",
    presentParticiple: "bringing",
    thirdPersonSingular: "brings",
  },
  build: {
    head: "build",
    preterite: "built",
    pastParticiple: "built",
    presentParticiple: "building",
    thirdPersonSingular: "builds",
  },
  buy: {
    head: "buy",
    preterite: "bought",
    pastParticiple: "bought",
    presentParticiple: "buying",
    thirdPersonSingular: "buys",
  },
  call: {
    head: "call",
    preterite: "called",
    pastParticiple: "called",
    presentParticiple: "calling",
    thirdPersonSingular: "calls",
  },
  carry: {
    head: "carry",
    preterite: "carried",
    pastParticiple: "carried",
    presentParticiple: "carrying",
    thirdPersonSingular: "carries",
  },
  change: {
    head: "change",
    preterite: "changed",
    pastParticiple: "changed",
    presentParticiple: "changing",
    thirdPersonSingular: "changes",
  },
  choose: {
    head: "choose",
    preterite: "chose",
    pastParticiple: "chosen",
    presentParticiple: "choosing",
    thirdPersonSingular: "chooses",
  },
  come: {
    head: "come",
    preterite: "came",
    pastParticiple: "come",
    presentParticiple: "coming",
    thirdPersonSingular: "comes",
  },
  consider: {
    head: "consider",
    preterite: "considered",
    pastParticiple: "considered",
    presentParticiple: "considering",
    thirdPersonSingular: "considers",
  },
  continue: {
    head: "continue",
    preterite: "continued",
    pastParticiple: "continued",
    presentParticiple: "continuing",
    thirdPersonSingular: "continues",
  },
  create: {
    head: "create",
    preterite: "created",
    pastParticiple: "created",
    presentParticiple: "creating",
    thirdPersonSingular: "creates",
  },
  decide: {
    head: "decide",
    preterite: "decided",
    pastParticiple: "decided",
    presentParticiple: "deciding",
    thirdPersonSingular: "decides",
  },
  describe: {
    head: "describe",
    preterite: "described",
    pastParticiple: "described",
    presentParticiple: "describing",
    thirdPersonSingular: "describes",
  },
  develop: {
    head: "develop",
    preterite: "developed",
    pastParticiple: "developed",
    presentParticiple: "developing",
    thirdPersonSingular: "develops",
  },
  die: {
    head: "die",
    preterite: "died",
    pastParticiple: "died",
    presentParticiple: "dying",
    thirdPersonSingular: "dies",
  },
  do: {
    head: "do",
    preterite: "did",
    pastParticiple: "done",
    presentParticiple: "doing",
    thirdPersonSingular: "does",
  },
  draw: {
    head: "draw",
    preterite: "drew",
    pastParticiple: "drawn",
    presentParticiple: "drawing",
    thirdPersonSingular: "draws",
  },
  drive: {
    head: "drive",
    preterite: "drove",
    pastParticiple: "driven",
    presentParticiple: "driving",
    thirdPersonSingular: "drives",
  },
  eat: {
    head: "eat",
    preterite: "ate",
    pastParticiple: "eaten",
    presentParticiple: "eating",
    thirdPersonSingular: "eats",
  },
  end: {
    head: "end",
    preterite: "ended",
    pastParticiple: "ended",
    presentParticiple: "ending",
    thirdPersonSingular: "ends",
  },
  explain: {
    head: "explain",
    preterite: "explained",
    pastParticiple: "explained",
    presentParticiple: "explaining",
    thirdPersonSingular: "explains",
  },
  fall: {
    head: "fall",
    preterite: "fell",
    pastParticiple: "fallen",
    presentParticiple: "falling",
    thirdPersonSingular: "falls",
  },
  feel: {
    head: "feel",
    preterite: "felt",
    pastParticiple: "felt",
    presentParticiple: "feeling",
    thirdPersonSingular: "feels",
  },
  find: {
    head: "find",
    preterite: "found",
    pastParticiple: "found",
    presentParticiple: "finding",
    thirdPersonSingular: "finds",
  },
  follow: {
    head: "follow",
    preterite: "followed",
    pastParticiple: "followed",
    presentParticiple: "following",
    thirdPersonSingular: "follows",
  },
  get: {
    head: "get",
    preterite: "got",
    pastParticiple: "gotten",
    presentParticiple: "getting",
    thirdPersonSingular: "gets",
  },
  give: {
    head: "give",
    preterite: "gave",
    pastParticiple: "given",
    presentParticiple: "giving",
    thirdPersonSingular: "gives",
  },
  go: {
    head: "go",
    preterite: "went",
    pastParticiple: "gone",
    presentParticiple: "going",
    thirdPersonSingular: "goes",
  },
  grow: {
    head: "grow",
    preterite: "grew",
    pastParticiple: "grown",
    presentParticiple: "growing",
    thirdPersonSingular: "grows",
  },
  happen: {
    head: "happen",
    preterite: "happened",
    pastParticiple: "happened",
    presentParticiple: "happening",
    thirdPersonSingular: "happens",
  },
  have: {
    head: "have",
    preterite: "had",
    pastParticiple: "had",
    presentParticiple: "having",
    thirdPersonSingular: "has",
  },
  hear: {
    head: "hear",
    preterite: "heard",
    pastParticiple: "heard",
    presentParticiple: "hearing",
    thirdPersonSingular: "hears",
  },
  help: {
    head: "help",
    preterite: "helped",
    pastParticiple: "helped",
    presentParticiple: "helping",
    thirdPersonSingular: "helps",
  },
  hold: {
    head: "hold",
    preterite: "held",
    pastParticiple: "held",
    presentParticiple: "holding",
    thirdPersonSingular: "holds",
  },
  hope: {
    head: "hope",
    preterite: "hoped",
    pastParticiple: "hoped",
    presentParticiple: "hoping",
    thirdPersonSingular: "hopes",
  },
  include: {
    head: "include",
    preterite: "included",
    pastParticiple: "included",
    presentParticiple: "including",
    thirdPersonSingular: "includes",
  },
  increase: {
    head: "increase",
    preterite: "increased",
    pastParticiple: "increased",
    presentParticiple: "increasing",
    thirdPersonSingular: "increases",
  },
  keep: {
    head: "keep",
    preterite: "kept",
    pastParticiple: "kept",
    presentParticiple: "keeping",
    thirdPersonSingular: "keeps",
  },
  know: {
    head: "know",
    preterite: "knew",
    pastParticiple: "known",
    presentParticiple: "knowing",
    thirdPersonSingular: "knows",
  },
  learn: {
    head: "learn",
    preterite: "learned",
    pastParticiple: "learned",
    presentParticiple: "learning",
    thirdPersonSingular: "learns",
  },
  leave: {
    head: "leave",
    preterite: "left",
    pastParticiple: "left",
    presentParticiple: "leaving",
    thirdPersonSingular: "leaves",
  },
  let: {
    head: "let",
    preterite: "let",
    pastParticiple: "let",
    presentParticiple: "letting",
    thirdPersonSingular: "lets",
  },
  like: {
    head: "like",
    preterite: "liked",
    pastParticiple: "liked",
    presentParticiple: "liking",
    thirdPersonSingular: "likes",
  },
  live: {
    head: "live",
    preterite: "lived",
    pastParticiple: "lived",
    presentParticiple: "living",
    thirdPersonSingular: "lives",
  },
  look: {
    head: "look",
    preterite: "looked",
    pastParticiple: "looked",
    presentParticiple: "looking",
    thirdPersonSingular: "looks",
  },
  lose: {
    head: "lose",
    preterite: "lost",
    pastParticiple: "lost",
    presentParticiple: "losing",
    thirdPersonSingular: "loses",
  },
  love: {
    head: "love",
    preterite: "loved",
    pastParticiple: "loved",
    presentParticiple: "loving",
    thirdPersonSingular: "loves",
  },
  make: {
    head: "make",
    preterite: "made",
    pastParticiple: "made",
    presentParticiple: "making",
    thirdPersonSingular: "makes",
  },
  mean: {
    head: "mean",
    preterite: "meant",
    pastParticiple: "meant",
    presentParticiple: "meaning",
    thirdPersonSingular: "means",
  },
  meet: {
    head: "meet",
    preterite: "met",
    pastParticiple: "met",
    presentParticiple: "meeting",
    thirdPersonSingular: "meets",
  },
  move: {
    head: "move",
    preterite: "moved",
    pastParticiple: "moved",
    presentParticiple: "moving",
    thirdPersonSingular: "moves",
  },
  need: {
    head: "need",
    preterite: "needed",
    pastParticiple: "needed",
    presentParticiple: "needing",
    thirdPersonSingular: "needs",
  },
  offer: {
    head: "offer",
    preterite: "offered",
    pastParticiple: "offered",
    presentParticiple: "offering",
    thirdPersonSingular: "offers",
  },
  open: {
    head: "open",
    preterite: "opened",
    pastParticiple: "opened",
    presentParticiple: "opening",
    thirdPersonSingular: "opens",
  },
  pay: {
    head: "pay",
    preterite: "paid",
    pastParticiple: "paid",
    presentParticiple: "paying",
    thirdPersonSingular: "pays",
  },
  play: {
    head: "play",
    preterite: "played",
    pastParticiple: "played",
    presentParticiple: "playing",
    thirdPersonSingular: "plays",
  },
  put: {
    head: "put",
    preterite: "put",
    pastParticiple: "put",
    presentParticiple: "putting",
    thirdPersonSingular: "puts",
  },
  read: {
    head: "read",
    preterite: "read",
    pastParticiple: "read",
    presentParticiple: "reading",
    thirdPersonSingular: "reads",
  },
  remember: {
    head: "remember",
    preterite: "remembered",
    pastParticiple: "remembered",
    presentParticiple: "remembering",
    thirdPersonSingular: "remembers",
  },
  run: {
    head: "run",
    preterite: "ran",
    pastParticiple: "run",
    presentParticiple: "running",
    thirdPersonSingular: "runs",
  },
  say: {
    head: "say",
    preterite: "said",
    pastParticiple: "said",
    presentParticiple: "saying",
    thirdPersonSingular: "says",
  },
  see: {
    head: "see",
    preterite: "saw",
    pastParticiple: "seen",
    presentParticiple: "seeing",
    thirdPersonSingular: "sees",
  },
  seem: {
    head: "seem",
    preterite: "seemed",
    pastParticiple: "seemed",
    presentParticiple: "seeming",
    thirdPersonSingular: "seems",
  },
  sell: {
    head: "sell",
    preterite: "sold",
    pastParticiple: "sold",
    presentParticiple: "selling",
    thirdPersonSingular: "sells",
  },
  send: {
    head: "send",
    preterite: "sent",
    pastParticiple: "sent",
    presentParticiple: "sending",
    thirdPersonSingular: "sends",
  },
  set: {
    head: "set",
    preterite: "set",
    pastParticiple: "set",
    presentParticiple: "setting",
    thirdPersonSingular: "sets",
  },
  show: {
    head: "show",
    preterite: "showed",
    pastParticiple: "shown",
    presentParticiple: "showing",
    thirdPersonSingular: "shows",
  },
  sit: {
    head: "sit",
    preterite: "sat",
    pastParticiple: "sat",
    presentParticiple: "sitting",
    thirdPersonSingular: "sits",
  },
  sleep: {
    head: "sleep",
    preterite: "slept",
    pastParticiple: "slept",
    presentParticiple: "sleeping",
    thirdPersonSingular: "sleeps",
  },
  speak: {
    head: "speak",
    preterite: "spoke",
    pastParticiple: "spoken",
    presentParticiple: "speaking",
    thirdPersonSingular: "speaks",
  },
  spend: {
    head: "spend",
    preterite: "spent",
    pastParticiple: "spent",
    presentParticiple: "spending",
    thirdPersonSingular: "spends",
  },
  stand: {
    head: "stand",
    preterite: "stood",
    pastParticiple: "stood",
    presentParticiple: "standing",
    thirdPersonSingular: "stands",
  },
  start: {
    head: "start",
    preterite: "started",
    pastParticiple: "started",
    presentParticiple: "starting",
    thirdPersonSingular: "starts",
  },
  stay: {
    head: "stay",
    preterite: "stayed",
    pastParticiple: "stayed",
    presentParticiple: "staying",
    thirdPersonSingular: "stays",
  },
  stop: {
    head: "stop",
    preterite: "stopped",
    pastParticiple: "stopped",
    presentParticiple: "stopping",
    thirdPersonSingular: "stops",
  },
  study: {
    head: "study",
    preterite: "studied",
    pastParticiple: "studied",
    presentParticiple: "studying",
    thirdPersonSingular: "studies",
  },
  take: {
    head: "take",
    preterite: "took",
    pastParticiple: "taken",
    presentParticiple: "taking",
    thirdPersonSingular: "takes",
  },
  talk: {
    head: "talk",
    preterite: "talked",
    pastParticiple: "talked",
    presentParticiple: "talking",
    thirdPersonSingular: "talks",
  },
  teach: {
    head: "teach",
    preterite: "taught",
    pastParticiple: "taught",
    presentParticiple: "teaching",
    thirdPersonSingular: "teaches",
  },
  tell: {
    head: "tell",
    preterite: "told",
    pastParticiple: "told",
    presentParticiple: "telling",
    thirdPersonSingular: "tells",
  },
  think: {
    head: "think",
    preterite: "thought",
    pastParticiple: "thought",
    presentParticiple: "thinking",
    thirdPersonSingular: "thinks",
  },
  throw: {
    head: "throw",
    preterite: "threw",
    pastParticiple: "thrown",
    presentParticiple: "throwing",
    thirdPersonSingular: "throws",
  },
  touch: {
    head: "touch",
    preterite: "touched",
    pastParticiple: "touched",
    presentParticiple: "touching",
    thirdPersonSingular: "touches",
  },
  travel: {
    head: "travel",
    preterite: "traveled",
    pastParticiple: "traveled",
    presentParticiple: "traveling",
    thirdPersonSingular: "travels",
  },
  try: {
    head: "try",
    preterite: "tried",
    pastParticiple: "tried",
    presentParticiple: "trying",
    thirdPersonSingular: "tries",
  },
  turn: {
    head: "turn",
    preterite: "turned",
    pastParticiple: "turned",
    presentParticiple: "turning",
    thirdPersonSingular: "turns",
  },
  understand: {
    head: "understand",
    preterite: "understood",
    pastParticiple: "understood",
    presentParticiple: "understanding",
    thirdPersonSingular: "understands",
  },
  use: {
    head: "use",
    preterite: "used",
    pastParticiple: "used",
    presentParticiple: "using",
    thirdPersonSingular: "uses",
  },
  wait: {
    head: "wait",
    preterite: "waited",
    pastParticiple: "waited",
    presentParticiple: "waiting",
    thirdPersonSingular: "waits",
  },
  walk: {
    head: "walk",
    preterite: "walked",
    pastParticiple: "walked",
    presentParticiple: "walking",
    thirdPersonSingular: "walks",
  },
  want: {
    head: "want",
    preterite: "wanted",
    pastParticiple: "wanted",
    presentParticiple: "wanting",
    thirdPersonSingular: "wants",
  },
  work: {
    head: "work",
    preterite: "worked",
    pastParticiple: "worked",
    presentParticiple: "working",
    thirdPersonSingular: "works",
  },
};

export { VERBS, MODAL_VERBS, SENTENCE_TYPES, SUBJECT_PRONOUNS };
