"use client";

import { useState, useEffect } from "react";

import { nanoid } from "nanoid";

import NormalVerbTriangle from "@/components/basic-triangles/verbs/normal-verb-triangle";
import ToBeVerbTriangle from "@/components/basic-triangles/verbs/to-be-verb-triangle";
import SelectDropdown from "@/components/ui/select-dropdown";

import { VERBS } from "@/lib/utils/words";

function BasicVerbTriangles() {
  // lightweight uuids generated by nanoid
  const [svgUseIds, setSvgUseIds] = useState(null);

  // verb options, the heaf form of the verb
  const [verbOptions, setVerbOptions] = useState(null);

  // the selected verb
  const [selectedVerb, setSelectedVerb] = useState(
    VERBS[Object.keys(VERBS)[0]],
  );

  // only run once when this component loads
  useEffect(() => {
    // generate unique ids for the SVG use commands
    const generateSvgUseIds = () => {
      return "01".split("").map((n) => nanoid());
    };
    const ids = generateSvgUseIds();
    setSvgUseIds(ids);

    // we want the head form of all verbs, except 'be'
    const verbOptions = Object.keys(VERBS).filter((k) => k !== "be");
    setVerbOptions(verbOptions);
  }, []);

  const handleVerbSelect = (key) => {
    setSelectedVerb(VERBS[key]);
  };

  if (svgUseIds === null) {
    return <p>Loading...</p>; // Render a placeholder while waiting
  }

  return (
    <div className="grid h-screen w-full grid-cols-2 grid-rows-[auto_1fr] border-2 border-black **:overflow-hidden">
      <SelectDropdown options={verbOptions} onSelect={handleVerbSelect} />
      <NormalVerbTriangle
        uuid={svgUseIds[0]}
        colour="black"
        verb={selectedVerb}
        visibility={{
          head: true,
          preterite: true,
          pastParticiple: true,
          presentParticiple: true,
          thirdPersonSingular: true,
          numbers: true,
        }}
        className="col-start-1 row-start-2"
      />
      <ToBeVerbTriangle
        uuid={svgUseIds[1]}
        colour="black"
        visibility={{
          head: true,
          pastParticiple: true,
          presentParticiple: true,
          am: true,
          is: true,
          are: true,
          was: true,
          were: true,
          numbers: true,
        }}
        className="col-start-2 row-start-2"
      />
    </div>
  );
}

export default BasicVerbTriangles;
