"use client";

import { useState, useEffect } from "react";

import { nanoid } from "nanoid";

import NormalPronounTriangle from "@/components/basic-triangles/pronouns/normal-pronoun-triangle";
import ToBePronounTriangle from "@/components/basic-triangles/pronouns/to-be-pronoun-triangle";
import SelectDropdown from "@/components/ui/select-dropdown";
import Card from "@/components/ui/card";

import { VERBS } from "@/lib/utils/words";

function BasicPronounTriangles() {
  // lightweight uuids generated by nanoid
  const [svgUseIds, setSvgUseIds] = useState(null);

  // verb options, the heaf form of the verb
  const [verbOptions, setVerbOptions] = useState(null);

  // the selected verb
  const [selectedVerb, setSelectedVerb] = useState(
    VERBS[Object.keys(VERBS)[0]],
  );

  // only run once when this component loads
  useEffect(() => {
    // generate unique ids for the SVG use commands
    const generateSvgUseIds = () => {
      return "01".split("").map((n) => nanoid());
    };
    const ids = generateSvgUseIds();
    setSvgUseIds(ids);

    // we want the head form of all verbs, except 'be'
    const verbOptions = Object.keys(VERBS).filter((k) => k !== "be");
    setVerbOptions(verbOptions);
  }, []);

  const handleVerbSelect = (key) => {
    setSelectedVerb(VERBS[key]);
  };

  if (svgUseIds === null) {
    return <p>Loading...</p>; // Render a placeholder while waiting for the ID
  }

  return (
    <div>
      <div className="flex h-auto flex-row items-center border-t-1 border-black">
        <SelectDropdown
          options={verbOptions}
          onSelect={handleVerbSelect}
          className="mx-auto py-2"
        />
      </div>
      <div className="grid h-screen w-full grid-cols-2 overflow-hidden border-2 border-red-500 bg-gray-300">
        <Card className="col-start-1 bg-white">
          <NormalPronounTriangle
            uuid={svgUseIds[0]}
            colour="black"
            verb={VERBS.eat}
            visibility={{
              triangle: true,
              head: true,
              headPronouns: true,
              preterite: true,
              preteritePronouns: true,
              thirdPersonSingular: true,
              thirdPersonSingularPronouns: true,
            }}
          />
        </Card>
        <Card className="col-start-2 bg-white">
          <ToBePronounTriangle
            uuid={svgUseIds[1]}
            colour="black"
            visibility={{
              triangle: true,
              am: true,
              amPronouns: true,
              are: true,
              arePronouns: true,
              is: true,
              isPronouns: true,
              was: true,
              wasPronouns: true,
              were: true,
              werePronouns: true,
            }}
          />
        </Card>
      </div>
    </div>
  );
}

export default BasicPronounTriangles;
