"use client";

import { useState, useEffect } from "react";

import { nanoid } from "nanoid";

import SelectDropdown from "@/components/ui/select-dropdown";
import SelectDropdownVerb from "@/components/ui/select-dropdown-verb";

import { VERBS } from "@/lib/grammar-data";
import { capitalizeFirstLetter } from "@/lib/utils/capatilize-first-letter";

/**
 * this container does 3 things
 * it generates unique ids for SVG use references
 * it allows selection of the boss verb
 * it shows the grammar diagram to the size of the window, for printing
 * @param {*} param0
 * @returns
 */

const SVG_USE_ID_COUNT = 20;
export const SVG_USE_ID_PLACEHOLDERS = [...Array(SVG_USE_ID_COUNT).keys()];

function GrammarContainer({
  sentenceTypes,
  showPronounsCombo,
  children,
  onVerbSelected,
  onSentenceTypeSelected,
  onShowPronounsSelected,
  onLoaded,
}) {
  // lightweight uuids generated by nanoid
  const [svgUseIds, setSvgUseIds] = useState(null);

  // sentence type options
  const [sentenceTypeOptions, setSentenceTypeOptions] = useState(null);

  // verb options, the head form of the verb
  const [verbOptions, setVerbOptions] = useState(null);

  // only run once when this component loads
  useEffect(() => {
    // generate unique ids for the SVG use commands
    // we will genrate 20 keys which is more than enough
    const generateSvgUseIds = () => {
      const uids = SVG_USE_ID_PLACEHOLDERS.map((n) => nanoid());
      return uids;
    };

    const ids = generateSvgUseIds();
    setSvgUseIds(ids);

    setSentenceTypeOptions(sentenceTypes);

    // we want all verbs except 'be'
    // regular verbs will be green
    // irregular verbs will be blue
    const allExceptBe = Object.keys(VERBS).filter((key) => key !== "be");
    const myVerbOptions = allExceptBe.map((key) => {
      const verb = VERBS[key];
      const isRegular = verb.preterite === verb.pastParticiple;
      return {
        key: verb.head,
        value: capitalizeFirstLetter(verb.head),
        isRegular,
      };
    });
    setVerbOptions(myVerbOptions);

    onLoaded(ids);
  }, []);

  const showPronounsOptions = ["false", "true"];

  const handleVerbSelect = (key) => {
    if (onVerbSelected) onVerbSelected(key);
  };
  const handleSentenceTypeSelect = (key) => {
    if (onSentenceTypeSelected) onSentenceTypeSelected(key);
  };
  const handleShowPronounsSelect = (key) => {
    if (onShowPronounsSelected) onShowPronounsSelected(key);
  };

  if (svgUseIds === null) {
    return <p>Loading...</p>; // Render a placeholder while waiting for the ID
  }

  return (
    <>
      <div className="grid h-auto grid-cols-[1fr_auto_auto_auto_1fr] items-center gap-4 border-t-1 border-black print:hidden">
        {sentenceTypeOptions && (
          <SelectDropdown
            title="Sentence Type:"
            options={sentenceTypeOptions}
            onSelect={handleSentenceTypeSelect}
            className="col-start-2 py-2"
          />
        )}
        <SelectDropdownVerb
          title="Boss Verb:"
          options={verbOptions}
          onSelect={handleVerbSelect}
          className="col-start-3 py-2"
        />
        {showPronounsCombo && (
          <SelectDropdown
            title="Show Pronouns:"
            options={showPronounsOptions}
            onSelect={handleShowPronounsSelect}
            className="col-start-4 py-2"
          />
        )}
      </div>
      <div className="relative flex h-screen w-full flex-col overflow-visible border-2 border-red-500 bg-gray-300">
        {children}
      </div>
    </>
  );
}

export default GrammarContainer;
