"use client";

import { useState, useEffect } from "react";

import { nanoid } from "nanoid";

import SelectDropdown from "@/components/ui/select-dropdown";

import { VERBS } from "@/lib/utils/grammar-data";

/**
 * this container does 3 things
 * it generates unique ids for SVG use references
 * it allows selection of the boss verb
 * it shows the grammar diagram to the size of the window, for printing
 * @param {*} param0
 * @returns
 */
function GrammarContainer({
  svgUseIdSeed,
  children,
  onVerbSelected,
  onLoaded,
}) {
  // lightweight uuids generated by nanoid
  const [svgUseIds, setSvgUseIds] = useState(null);

  // verb options, the heaf form of the verb
  const [verbOptions, setVerbOptions] = useState(null);

  // only run once when this component loads
  useEffect(() => {
    // generate unique ids for the SVG use commands
    const generateSvgUseIds = () => {
      return svgUseIdSeed.split("").map((n) => nanoid());
    };
    const ids = generateSvgUseIds();
    setSvgUseIds(ids);

    // we want the head form of all verbs, except 'be'
    const verbOptions = Object.keys(VERBS).filter((k) => k !== "be");
    setVerbOptions(verbOptions);

    onLoaded(ids);
  }, []);

  const handleVerbSelect = (key) => {
    //setSelectedVerb(VERBS[key]);
    onVerbSelected(key);
  };

  if (svgUseIds === null) {
    return <p>Loading...</p>; // Render a placeholder while waiting for the ID
  }

  return (
    <>
      <div className="flex h-auto flex-row items-center border-t-1 border-black">
        <SelectDropdown
          title="Boss Verb:"
          options={verbOptions}
          onSelect={handleVerbSelect}
          className="mx-auto py-2"
        />
      </div>
      <div className="relative flex h-screen w-full flex-col overflow-visible border-2 border-red-500 bg-gray-300">
        {children}
      </div>
    </>
  );
}

export default GrammarContainer;
